### ISSUE TITLE
Incorrect python 3.13

### ISSUE THREAD

**Issue by Ulmo-F** [ameli/manylinux-cuda#7]
First, thank you for maintaining these images.

I get an error when importing numpy (same with scipy) for python 3.13 in all your x86_64 images.

The most relevent line should be :
`ImportError: /venv/lib/python3.13/site-packages/numpy/_core/_multiarray_umath.cpython-313-x86_64-linux-gnu.so: undefined symbol: PyMutex_Unlock`

python 3.7 - 3.13 seems to work correctly.

python3.13/numpy works correctly with the quay.io/pypa/manylinux* images.
[At a first glance it seems that your images are not based upon the latest quay.io/pypa version]

### Steps to reproduce :
```
docker run -it sameli/manylinux2014_x86_64_cuda_12.3 bash

/usr/local/bin/python3.13 -m venv venv
source venv/bin/activate
pip install numpy
python

import numpy
```

**Comment by ameli** [comment]
Thank you for your question.

This issue is not due to any error in the images. Python 3.13 in all images prior to October 2024 (the official release of Python 3.13), was a pre-release version.

Additionally, as of June 2024, **manylinux2014** reached its [end of life](https://github.com/mayeut/pep600_compliance/blob/master/EOL.rst), which predates the official release of Python 3.13.

To resolve this issue, I recommend using the ``manylinux_2_34_x86_64_cuda_12.6`` image, which includes the official Python 3.13 release and is compatible with NumPy.

    docker run -it sameli/manylinux_2_34_x86_64_cuda_12.6 bash

**Comment by ameli** [comment]
I'll close this thread, but feel free to reopen it if the above solution doesn't work for you.

**Comment by Ulmo-F** [comment]
I'm afraid I wasn't clear.

Importing numpy with python 3.13 fails with your images (except the last one manylinux_2_34_x86_64_cuda_12.6).

It does work with the upward images quay.io/pypa/manylinux*

It does with an image build locally with your very script.

I suspect the quay.io images have evolved, including some updates/fixes, since you build and published your images.

**Comment by ameli** [comment]
You're right; I rebuilt the images and checked the one in your original post. It seems to be working now. Thanks for pointing that out.
